language: python
python:
  - "2.7"
  - "3.6"
install:
  - pip install -r requirements.txt 
  - make
  - python setup.py install
# command to run tests
script: cd tests && python -m unittest test-xml test-attribute-vector test-dictionary
